export const TestsData = [
    {
        id: "af87456b-87a1-412a-b2f4-d3f1d7b0b8e1",
        name: "general-knowledge-test",
        duration: "30",
        evaluationType: "Automated",
        totalScore: "40",
        questions: [
            {
                question: "Who was the first president of the United States?",
                type: "Multiple Choice",
                options: [
                    "George Washington",
                    "Abraham Lincoln",
                    "Thomas Jefferson",
                    "John Adams",
                ],
                correctAnswer: "George Washington",
                score: "10",
            },
            {
                question: "Is the Earth the third planet from the Sun?",
                type: "True/False",
                options: ["", "", "", ""],
                correctAnswer: "True",
                score: "10",
            },
            {
                question: "Which country is known as the Land of the Rising Sun?",
                type: "Multiple Choice",
                options: ["China", "Japan", "South Korea", "India"],
                correctAnswer: "Japan",
                score: "10",
            },
            {
                question: "The Great Wall of China is located in which country?",
                type: "Multiple Choice",
                options: ["China", "India", "Russia", "Vietnam"],
                correctAnswer: "China",
                score: "10",
            },
        ],
        assignedClasses: [],
        studentsAttempted: 0,
        assignedTo: [],
    },
    {
        id: "a7289f1b-28c9-4569-927b-9cf34ed5c1f2",
        name: "math-test",
        duration: "30",
        evaluationType: "Manual",
        totalScore: "40",
        questions: [
            {
                question: "What is 9 * 7?",
                type: "Multiple Choice",
                options: ["56", "63", "72", "77"],
                correctAnswer: "63",
                score: "10",
            },
            {
                question: "What is the square root of 144?",
                type: "Multiple Choice",
                options: ["12", "14", "16", "18"],
                correctAnswer: "12",
                score: "10",
            },
            {
                question: "Is 21 a prime number?",
                type: "True/False",
                options: ["", "", "", ""],
                correctAnswer: "False",
                score: "10",
            },
            {
                question: "What is 15 + 25?",
                type: "Multiple Choice",
                options: ["35", "40", "45", "50"],
                correctAnswer: "40",
                score: "10",
            },
        ],
        assignedClasses: [],
        studentsAttempted: 0,
        assignedTo: [],
    },
    {
        id: "bc9a7851-b340-4cdb-b12f-e4bfe2676b7d",
        name: "science-test",
        duration: "45",
        totalScore: "40",
        evaluationType: "AI",
        questions: [
            {
                question: "What is the chemical symbol for water?",
                type: "Multiple Choice",
                options: ["H2O", "O2", "CO2", "HO"],
                correctAnswer: "H2O",
                score: "10",
            },
            {
                question: "Is the Sun a star?",
                type: "True/False",
                options: ["", "", "", ""],
                correctAnswer: "True",
                score: "10",
            },
            {
                question: "What is the center of an atom called?",
                type: "Multiple Choice",
                options: ["Nucleus", "Proton", "Electron", "Neutron"],
                correctAnswer: "Nucleus",
                score: "10",
            },
            {
                question:
                    "Which gas do plants primarily absorb from the atmosphere for photosynthesis?",
                type: "Multiple Choice",
                options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
                correctAnswer: "Carbon Dioxide",
                score: "10",
            },
        ],
        assignedClasses: [],
        studentsAttempted: 0,
        assignedTo: [],
    },
    {
        id: "abf1a2ff-b33a-4710-8a28-1ef073563bd2",
        name: "coding-test",
        evaluationType: "Automated",
        duration: "60",
        totalScore: "40",
        questions: [
            {
                question:
                    "Which of the following is the correct syntax to define a function in Python?",
                type: "Multiple Choice",
                options: [
                    "function myFunction() {}",
                    "def myFunction():",
                    "def myFunction[]",
                    "function:myFunction()",
                ],
                correctAnswer: "def myFunction():",
                score: "10",
            },
            {
                question:
                    "What is the output of the following Python code: print(2 + 3 * 2)?",
                type: "Multiple Choice",
                options: ["8", "10", "12", "6"],
                correctAnswer: "8",
                score: "10",
            },
            {
                question: "What keyword is used to define a class in Python?",
                type: "Multiple Choice",
                options: ["class", "def", "struct", "object"],
                correctAnswer: "class",
                score: "10",
            },
            {
                question: "Which of the following is a Python collection type?",
                type: "Multiple Choice",
                options: ["List", "Array", "Set", "Both List and Set"],
                correctAnswer: "Both List and Set",
                score: "10",
            },
        ],
        assignedClasses: [],
        studentsAttempted: 0,
        assignedTo: [],
    },
    {
        id: "d497dbf5-d953-49d9-b070-bb7226fa08be",
        name: "chemistry-test",
        duration: "45",
        evaluationType: "Manual",
        totalScore: "40",
        questions: [
            {
                question: "What is the chemical symbol for Sodium?",
                type: "Multiple Choice",
                options: ["Na", "So", "S", "Ne"],
                correctAnswer: "Na",
                score: "10",
            },
            {
                question: "What is the atomic number of Carbon?",
                type: "Multiple Choice",
                options: ["6", "12", "8", "14"],
                correctAnswer: "6",
                score: "10",
            },
            {
                question: "Is water a good conductor of electricity?",
                type: "True/False",
                options: ["", "", "", ""],
                correctAnswer: "False",
                score: "10",
            },
            {
                question: "Which of these elements is a noble gas?",
                type: "Multiple Choice",
                options: ["Oxygen", "Argon", "Nitrogen", "Hydrogen"],
                correctAnswer: "Argon",
                score: "10",
            },
        ],
        assignedClasses: [],
        studentsAttempted: 0,
        assignedTo: [],
    },
];